version: '3.8'

services:
  #   Web Server Service
  user-service-webserver:
    image: nginx:stable-alpine
    container_name: user-service-webserver
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - user-service
      - api-gateway_app-shared

    # Application Service
  user-service:
    container_name: user-service
    image: digitalocean.com/php
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "9002:9000"
    environment:
      SERVICE_NAME: user-service
      SERVICE_TAGS: dev
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - user-service
      - api-gateway_app-shared

  db:
    image: mysql:latest
    container_name: user-service-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - user-service

networks:
  user-service:
  api-gateway_app-shared:
    external: true

volumes:
  dbdata:
    driver: local