version: '3.8'

services:
#   Web Server Service
  book-service-webserver:
    image: nginx:stable-alpine
    container_name: book-service-webserver
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - book-service
        - api-gateway_app-shared

    # Application Service
  book-service:
    container_name: book-service
    image: digitalocean.com/php
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "9001:9000"
    environment:
      SERVICE_NAME: book-service
      SERVICE_TAGS: dev
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
        - book-service
        - api-gateway_app-shared

networks:
    book-service:
    api-gateway_app-shared:
      external: true
